### ISSUE TITLE
el-tooltip not working on disabled el-button

### ISSUE THREAD

**Issue by xfudox** [ElementUI/awesome-element#38]
When el-button (only child) inside el-tooltip is disabled, el-tooltip won't show anything.

Is this normal/desired behavior?

I would like to show tooltip with information on why button is disabled, so el-tooltip need to be enabled only when el-button is disabled.

**Comment by ChristianGiupponi** [comment]
I have the same problem, any update on this?

**Comment by xfudox** [comment]
bump

**Comment by sunchenguang** [comment]
same issue

**Comment by sunchenguang** [comment]
just use span to wrap disabled button 
`<span><el-button disabled></el-button></span>`

**Comment by FabioRNobrega** [comment]
> just use span to wrap disabled button
> `<span><el-button disabled></el-button></span>`

Thanks alot @sunchenguang. :heart:

**Comment by cstuncsik** [comment]
Still happening with version 2.15.12

**Comment by alberttocastro** [comment]
> just use span to wrap disabled button `<span><el-button disabled></el-button></span>`

That worked for me
